import {motion} from 'framer-motion'; import {ArrowDown,ArrowUpRight} from 'lucide-react'; import Nav from './components/Nav'; import {coaches} from './data/coaches';
const reveal={initial:{opacity:0,y:45},whileInView:{opacity:1,y:0},viewport:{once:true,amount:.18},transition:{duration:.8,ease:[.22,1,.36,1]}};
function Coach({c,i}){return <motion.article {...reveal} className={'coach '+(i%2?'reverse':'')} id={c.id}><div className="coachImage"><img src={c.image}/><span>{c.number}</span></div><div className="coachText"><div className="eyebrow">{c.code} / {c.role}</div><h3>{c.name}</h3><div className="professionalBackground">{c.background}</div><p className="quote">{c.quote}</p><p>{c.copy}</p><a href="#contact">COACH PROFILE <ArrowUpRight size={16}/></a></div></motion.article>}
export default function App(){return <main id="top"><Nav/><section className="hero"><img src="/assets/hero.jpg"/><div className="veil"/><motion.div className="heroCopy" initial={{opacity:0,y:35}} animate={{opacity:1,y:0}} transition={{duration:1,delay:.25}}><div className="eyebrow light">INDIA · GERMANY · UNITED KINGDOM</div><h1>THREE COACHES.<br/><em>ONE LEGACY.</em></h1><p>A family shaped by tennis. Three coaching journeys across three countries, united by one standard.</p></motion.div><a className="scroll" href="#legacy"><ArrowDown/> DISCOVER</a></section>
<section id="legacy" className="intro"><motion.div {...reveal}><div className="eyebrow">THE LEGACY / EST. THROUGH GENERATIONS</div><h2>Tennis is not simply<br/>what we teach.<br/><em>It is what connects us.</em></h2></motion.div><motion.div {...reveal} className="introSide"><img src="/assets/legacy-logo.png"/><p>From India to Germany to the United Kingdom, The Shaikh Academy represents a family coaching legacy — distinct experiences, one shared commitment to developing players with purpose.</p></motion.div></section>
<section className="statement"><motion.p {...reveal}>BUILT ON <span>FOUNDATION.</span><br/>DRIVEN BY <span>PROGRESS.</span><br/>DEFINED BY <span>THE PLAYER.</span></motion.p></section>
<section id="coaches" className="coaches"><div className="sectionHead"><span>01</span><h2>THE COACHES</h2><p>Three countries.<br/>One coaching lineage.</p></div>{coaches.map((c,i)=><Coach key={c.id} c={c} i={i}/>)}</section>
<section id="coaching" className="coaching"><div className="sectionHead"><span>02</span><h2>COACHING</h2><p>Development with purpose.<br/>Built around the player.</p></div><motion.div {...reveal} className="coachingIntro"><h2>Every player has<br/><em>a different game.</em></h2><p>Our coaching is built around the individual — developing strong foundations, better decision-making and the confidence to compete. From learning the game to pursuing higher performance, every session has a purpose.</p></motion.div><div className="coachingServices"><motion.div {...reveal}><span>01</span><h3>Private Coaching</h3><p>Individual sessions focused on the technical, tactical and competitive needs of the player.</p></motion.div><motion.div {...reveal}><span>02</span><h3>Junior Development</h3><p>Building strong fundamentals, confidence and an understanding of the game from an early stage.</p></motion.div><motion.div {...reveal}><span>03</span><h3>Performance Training</h3><p>Purposeful training for competitive players looking to develop their game and perform under pressure.</p></motion.div></div><a className="coachingLink" href="#contact">ENQUIRE ABOUT COACHING <ArrowUpRight size={16}/></a></section>
<section id="philosophy" className="philosophy"><div className="sectionHead dark"><span>02</span><h2>OUR PHILOSOPHY</h2></div><motion.div {...reveal} className="philoGrid"><h2>Build the player.<br/><em>Not just the stroke.</em></h2><div><p>Technique creates a foundation. Decision-making gives it purpose. Competition gives it meaning.</p><p>Our approach respects the fundamentals while developing adaptable players who understand the game, compete with confidence and continue learning beyond the lesson.</p></div></motion.div><div className="principles"><div><b>01</b><span>FOUNDATION</span></div><div><b>02</b><span>INTELLIGENCE</span></div><div><b>03</b><span>COMPETITION</span></div></div></section>
<section className="countries"><motion.div {...reveal}><span>IND</span><h3>INDIA</h3><p>Where the foundation began.</p></motion.div><motion.div {...reveal}><span>GER</span><h3>GERMANY</h3><p>Where the perspective expanded.</p></motion.div><motion.div {...reveal}><span>GBR</span><h3>UNITED KINGDOM</h3><p>Where the next chapter grows.</p></motion.div></section>
<section id="contact" className="contact"><motion.div {...reveal}><div className="eyebrow light">THE NEXT POINT STARTS HERE</div><h2>LET'S<br/><em>PLAY.</em></h2><p>Coaching, collaboration and academy enquiries.</p><a href="mailto:hello@theshaikhacademy.com">GET IN TOUCH <ArrowUpRight/></a></motion.div></section>
<footer><div className="footerBrand"><img src="/assets/legacy-logo.png"/><span>THE SHAIKH ACADEMY</span></div><p>INDIA · GERMANY · UNITED KINGDOM</p><p>© 2026 THE SHAIKH ACADEMY</p></footer></main>}
